package com.hiczp.minecraft.protocol.data

import com.hiczp.minecraft.protocol.model.MinecraftProtocol
import com.hiczp.minecraft.protocol.model.packet.ConfigurationUpdateTagsPacket
import com.hiczp.minecraft.protocol.model.packet.FeatureFlagsPacket
import com.hiczp.minecraft.protocol.model.packet.RegistryDataPacket
import com.hiczp.minecraft.protocol.model.type.KnownPack

/**
 * The official vanilla protocol-data snapshot for [MinecraftProtocol].
 *
 * Its encoded input is generated by negotiating Configuration twice with the
 * matching official server: once with all offered Known Packs accepted and
 * once with none accepted.
 */
sealed class VanillaProtocolData private constructor() : ProtocolDataSet {
    companion object Default : VanillaProtocolData() {
        private val snapshot: VanillaConfigurationSnapshot by lazy(
            LazyThreadSafetyMode.PUBLICATION,
        ) {
            decodeVanillaConfigurationSnapshot()
        }

        override val minecraftVersion: String
            get() = MinecraftProtocol.MINECRAFT_VERSION

        override val protocolVersion: Int
            get() = MinecraftProtocol.PROTOCOL_VERSION

        override val knownPacks: List<KnownPack>
            get() = snapshot.knownPacks

        override val featureFlags: FeatureFlagsPacket
            get() = snapshot.featureFlags

        override val tags: ConfigurationUpdateTagsPacket
            get() = snapshot.tags

        override fun registryPackets(
            clientKnownPacks: List<KnownPack>,
        ): List<RegistryDataPacket> =
            if (clientKnownPacks == knownPacks) {
                snapshot.clientKnownRegistries
            } else {
                snapshot.completeRegistries
            }
    }
}
