package com.hiczp.minecraft.protocol.configuration.vanilla

import com.hiczp.minecraft.protocol.configuration.*
import com.hiczp.minecraft.protocol.model.MinecraftProtocol
import com.hiczp.minecraft.protocol.model.packet.ClientboundRegistryDataPacket
import com.hiczp.minecraft.protocol.model.type.*
import com.hiczp.minecraft.world.format.datapack.DataPackFormatVersion

/**
 * The official vanilla protocol-data snapshot for [MinecraftProtocol].
 *
 * Its encoded input is generated by negotiating Configuration twice with the
 * matching official server: once with all offered Known Packs accepted and
 * once with none accepted.
 */
object VanillaConfigurationData : ConfigurationData {
    val dataPackFormatVersion: DataPackFormatVersion = DataPackFormatVersion(
        VanillaConfigurationPacketPayloads.dataPackFormatMajor,
        VanillaConfigurationPacketPayloads.dataPackFormatMinor,
    )

    /** Release-matched JSON-to-NBT projectors for every vanilla registry synchronized during Configuration. */
    val dataPackRegistryProjectors: List<DataPackRegistryProjector> by lazy(LazyThreadSafetyMode.PUBLICATION) {
        synchronizedRegistryPackets(emptyList()).map { clientboundRegistryDataPacket ->
            DataPackRegistryProjector(
                registryId = clientboundRegistryDataPacket.registry,
                dataPackRegistryEntryProjector = vanillaDataPackRegistryEntryProjector,
            )
        }
    }

    private val vanillaConfigurationSnapshot: VanillaConfigurationSnapshot by lazy(
        LazyThreadSafetyMode.PUBLICATION,
    ) {
        decodeVanillaConfigurationSnapshot()
    }

    override val offeredKnownPacks: List<KnownPack>
        get() = vanillaConfigurationSnapshot.offeredKnownPacks

    override val enabledFeatureFlags: Set<Identifier>
        get() = vanillaConfigurationSnapshot.enabledFeatureFlags

    override val registryTags: List<RegistryTags>
        get() = vanillaConfigurationSnapshot.registryTags

    override val staticRegistrySchema: StaticRegistrySchema
        get() = VanillaRegistryData.staticRegistrySchema

    override val completePacketCodecContext: PacketCodecContext
        get() = vanillaPacketCodecContext

    override fun synchronizedRegistryPackets(
        acceptedKnownPacks: List<KnownPack>,
    ): List<ClientboundRegistryDataPacket> =
        if (acceptedKnownPacks == offeredKnownPacks) {
            vanillaConfigurationSnapshot.knownPackSynchronizedRegistryPackets
        } else {
            vanillaConfigurationSnapshot.completeSynchronizedRegistryPackets
        }

    /** Data-pack-related Configuration values for a vanilla client that accepts the offered Known Packs. */
    val dataPackConfigurationSnapshot: DataPackConfigurationSnapshot by lazy(LazyThreadSafetyMode.PUBLICATION) {
        DataPackConfigurationSnapshot(
            offeredKnownPacks = offeredKnownPacks,
            enabledFeatureFlags = enabledFeatureFlags,
            synchronizedRegistryPackets = synchronizedRegistryPackets(offeredKnownPacks),
            registryTags = registryTags,
        )
    }

    /** Registry and tag view resolved from [dataPackConfigurationSnapshot]. */
    val clientRegistryView: ClientRegistryView by lazy(LazyThreadSafetyMode.PUBLICATION) {
        dataPackConfigurationSnapshot.resolveClientRegistryView(this)
    }

    private val vanillaPacketCodecContext: PacketCodecContext by lazy(
        LazyThreadSafetyMode.PUBLICATION,
    ) {
        VanillaRegistryData.packetCodecContext.withSynchronizedRegistries(
            vanillaConfigurationSnapshot.completeSynchronizedRegistryPackets,
        )
    }
}
