package com.hiczp.minecraft.protocol.datapack.vanilla

import com.hiczp.minecraft.protocol.datapack.ClientRegistryView
import com.hiczp.minecraft.protocol.datapack.DataPackConfigurationSnapshot
import com.hiczp.minecraft.protocol.datapack.ProtocolData
import com.hiczp.minecraft.protocol.datapack.resolveClientRegistryView
import com.hiczp.minecraft.protocol.model.MinecraftProtocol
import com.hiczp.minecraft.protocol.model.packet.RegistryDataPacket
import com.hiczp.minecraft.protocol.model.type.*

/**
 * The official vanilla protocol-data snapshot for [MinecraftProtocol].
 *
 * Its encoded input is generated by negotiating Configuration twice with the
 * matching official server: once with all offered Known Packs accepted and
 * once with none accepted.
 */
object VanillaProtocolData : ProtocolData {
    private val vanillaConfigurationSnapshot: VanillaConfigurationSnapshot by lazy(
        LazyThreadSafetyMode.PUBLICATION,
    ) {
        decodeVanillaConfigurationSnapshot()
    }

    override val offeredKnownPacks: List<KnownPack>
        get() = vanillaConfigurationSnapshot.offeredKnownPacks

    override val enabledFeatureFlags: Set<Identifier>
        get() = vanillaConfigurationSnapshot.enabledFeatureFlags

    override val registryTags: List<RegistryTags>
        get() = vanillaConfigurationSnapshot.registryTags

    override val staticRegistrySchema: StaticRegistrySchema
        get() = VanillaRegistryData.staticRegistrySchema

    override val completeProtocolRegistryContext: ProtocolRegistryContext
        get() = vanillaProtocolRegistryContext

    override fun synchronizedRegistryPackets(
        acceptedKnownPacks: List<KnownPack>,
    ): List<RegistryDataPacket> =
        if (acceptedKnownPacks == offeredKnownPacks) {
            vanillaConfigurationSnapshot.knownPackSynchronizedRegistryPackets
        } else {
            vanillaConfigurationSnapshot.completeSynchronizedRegistryPackets
        }

    /** Data-pack-related Configuration values for a vanilla client that accepts the offered Known Packs. */
    val dataPackConfigurationSnapshot: DataPackConfigurationSnapshot by lazy(LazyThreadSafetyMode.PUBLICATION) {
        DataPackConfigurationSnapshot(
            offeredKnownPacks = offeredKnownPacks,
            enabledFeatureFlags = enabledFeatureFlags,
            synchronizedRegistryPackets = synchronizedRegistryPackets(offeredKnownPacks),
            registryTags = registryTags,
        )
    }

    /** Registry and tag view resolved from [dataPackConfigurationSnapshot]. */
    val clientRegistryView: ClientRegistryView by lazy(LazyThreadSafetyMode.PUBLICATION) {
        dataPackConfigurationSnapshot.resolveClientRegistryView(this)
    }

    private val vanillaProtocolRegistryContext: ProtocolRegistryContext by lazy(
        LazyThreadSafetyMode.PUBLICATION,
    ) {
        val staticProtocolRegistryContext = VanillaRegistryData.protocolRegistryContext
        val protocolRegistries = staticProtocolRegistryContext.registries.toMutableMap()
        vanillaConfigurationSnapshot.completeSynchronizedRegistryPackets.forEach { registryDataPacket ->
            protocolRegistries[registryDataPacket.registryId] = ProtocolRegistry(
                registryDataPacket.registryId,
                registryDataPacket.entries.mapIndexed { rawId, registryEntry ->
                    ProtocolRegistryEntry(registryEntry.id, rawId)
                },
            )
        }
        ProtocolRegistryContext(
            registries = protocolRegistries,
            blockStates = staticProtocolRegistryContext.blockStates,
        )
    }
}
